name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - FireStore # Se dispara automáticamente al subir cambios a esta rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de Código
        uses: actions/checkout@v4

      - name: Desplegar en Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAGI_SUITE }}
          projectId: test-89a00
          channelId: live # Despliegue en vivo en magi-suite.web.app
