name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - FireStore # Se dispara automáticamente al subir cambios a esta rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de Código
        uses: actions/checkout@v4

      - name: Instalar dependencias de funciones
        run: |
          cd functions
          npm install

      - name: Desplegar en Firebase (Funciones, Hosting e Índices)
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project test-89a00 --force 
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAGI_SUITE }}
